server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerceDb
    username: youssef
    password: 08101999

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true